sphereon:
  cas:
    did:
      auth:
        appId: AlfrescoIntegration
        appDid: did:ethr:0x88ed694ffe9244e2993d2932638a5c736371fc04
        didMapUrl: https://mapping.did.alfresco.dev.sphereon.com
        didTransportsUrl: https://transports.did.alfresco.dev.sphereon.com
        appSecret: 2106b0925c0b7486d3474ea0521f0a8750992902c7a13f02498e4066da3cf0f0
        baseCasUrl: https://cas.dev.sphereon.com/cas

tomcat:
  protocol:
    ajp: true

